import { NgModule } from '@angular/core';
import { NativeScriptRouterModule } from 'nativescript-angular/router';
import { Routes, RouterModule } from '@angular/router';
import { AutoGeneratedComponent } from './auto-generated/auto-generated.component';
import { ListComponent } from './components/list/list.component.tns';
import { CreateComponent } from './components/create/create.component.tns';
import { LoginComponent } from './components/login/login.component';
import { AuthenticateComponent } from './components/authenticate/authenticate.component';
import { FeaturedComponent } from './components/featured/featured.component';
import { ItemComponent } from './components/item/item.component';
import { BrowseComponent } from './components/browse/browse.component';
import { CategoryComponent } from './components/category/category.component';
import { SearchComponent } from './components/search/search.component';
import { DetailComponent } from './components/detail/detail.component';

const routes: Routes = [
  // { path: "", component: LoginComponent },
  // { path: "authenticated", component: AuthenticateComponent }
  // { path: "", component: ListComponent },
  // { path: "create", component: CreateComponent }
  { path: "", redirectTo: "/featured", pathMatch: "full" },
  { path: "featured", component: FeaturedComponent },
  { path: "item", component: ItemComponent },
  { path: "browse", component: BrowseComponent },
  { path: "category", component: CategoryComponent },
  { path: "search", component: SearchComponent },
  { path: "list", component: ListComponent },
  { path: "detail/:id", component: DetailComponent }
];

@NgModule({
  imports: [NativeScriptRouterModule.forRoot(routes)],
  exports: [NativeScriptRouterModule]
})
export class AppRoutingModule { }
