import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { AutoGeneratedComponent } from './auto-generated/auto-generated.component';
import { ListComponent } from './components/list/list.component';
import { CreateComponent } from './components/create/create.component';
import { LoginComponent } from './components/login/login.component';
import { AuthenticateComponent } from './components/authenticate/authenticate.component';

const routes: Routes = [
  // { path: "", component: LoginComponent },
  // { path: "authenticated", component: AuthenticateComponent }
  { path: "", component: ListComponent },
  { path: "create", component: CreateComponent }
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
