import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { AutoGeneratedComponent } from './auto-generated/auto-generated.component';
import { ListComponent } from './components/list/list.component';
import { CreateComponent } from './components/create/create.component';

const routes: Routes = [
  // {
  //   path: '',
  //   redirectTo: '/auto-generated',
  //   pathMatch: 'full',
  // },
  // {
  //   path: 'auto-generated',
  //   component: AutoGeneratedComponent,
  // },
  { path: "", component: ListComponent },
  { path: "create", component: CreateComponent }
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
