import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';


import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { AutoGeneratedComponent } from './auto-generated/auto-generated.component';
import { ListComponent } from './components/list/list.component';
import { CreateComponent } from './components/create/create.component';
import { LoginComponent } from './components/login/login.component';
import { AuthenticateComponent } from './components/authenticate/authenticate.component';
// import { FeaturedComponent } from './components/featured/featured.component';
// import { ItemComponent } from './components/item/item.component';
// import { BrowseComponent } from './components/browse/browse.component';
// import { CategoryComponent } from './components/category/category.component';
// import { SearchComponent } from './components/search/search.component';

@NgModule({
  declarations: [
    AppComponent,
    AutoGeneratedComponent,
    ListComponent,
    CreateComponent,
    LoginComponent,
    AuthenticateComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpClientModule,
    AppRoutingModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
