import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { NativeScriptModule } from 'nativescript-angular/nativescript.module';
import { NativeScriptUISideDrawerModule } from "nativescript-ui-sidedrawer/angular";
import { BarcodeScanner } from 'nativescript-barcodescanner';

import { AppRoutingModule } from './app-routing.module.tns';
import { AppComponent } from './app.component.tns';
import { AutoGeneratedComponent } from './auto-generated/auto-generated.component';

// Uncomment and add to NgModule imports if you need to use two-way binding
import { NativeScriptFormsModule } from 'nativescript-angular/forms';

// Uncomment and add to NgModule imports  if you need to use the HTTP wrapper
import { NativeScriptHttpClientModule } from 'nativescript-angular/http-client';
import { ListComponent } from './components/list/list.component.tns';
import { CreateComponent } from './components/create/create.component.tns';
import { LoginComponent } from './components/login/login.component';
import { AuthenticateComponent } from './components/authenticate/authenticate.component';
import { FeaturedComponent } from './components/featured/featured.component';
import { ItemComponent } from './components/item/item.component';
import { BrowseComponent } from './components/browse/browse.component';
import { CategoryComponent } from './components/category/category.component';
import { SearchComponent } from './components/search/search.component';
import { ScannerComponent } from './components/scanner/scanner.component';
import { MenuComponent } from './components/menu/menu.component';
import { DetailComponent } from './components/detail/detail.component';
import { CartComponent } from './components/cart/cart.component';
import { ValuesPipe } from './shared/filter/value.pipe';
import { ProfileComponent } from './components/merchant/profile/profile.component';

@NgModule({
  declarations: [
    AppComponent,
    AutoGeneratedComponent,
    ListComponent,
    CreateComponent,
    LoginComponent,
    AuthenticateComponent,
    FeaturedComponent,
    ItemComponent,
    BrowseComponent,
    CategoryComponent,
    SearchComponent,
    ScannerComponent,
    MenuComponent,
    DetailComponent,
    CartComponent,
    ValuesPipe,
    ProfileComponent
  ],
  imports: [
    NativeScriptModule,
    NativeScriptFormsModule,
    NativeScriptHttpClientModule,
    NativeScriptUISideDrawerModule,
    AppRoutingModule,
  ],
  providers: [BarcodeScanner],
  bootstrap: [AppComponent],
  schemas: [NO_ERRORS_SCHEMA]
})
/*
Pass your application module to the bootstrapModule function located in main.ts to start your app
*/
export class AppModule { }
